### PR TITLE
#17: Extended the evaluate with a number-format attribute and checked in a unit test that this works in a toc-entry-on-resumed

### PR DESCRIPTION
**Pull request by PaulRambags**
Solves #17.

@kalaspuffar @bertfrees Please review this pull request. Many thanks!

### CODE REVIEW

**Comment by PaulRambags** [comment]
The build fails because of changes in the API.

**Comment by bertfrees** [comment]
Hmm it just occurred to me that we already have a [`numeral-format`](http://braillespecs.github.io/obfl/obfl-evaluation-language.html#L3682) function in the OBFL evaluation language. That actually removes the whole need for a special attribute. How did we miss that?

**Comment by bertfrees** [comment]
Using `(numeral-format ...)` is actually also more elegant because that way you are actually formatting numbers, not strings.

**Comment by PaulRambags** [comment]
>Hmm it just occurred to me that we already have a `numeral-format` function in the OBFL evaluation language. That actually removes the whole need for a special attribute. How did we miss that?

This actually makes this whole PR unneeded, and the corresponding one in `dotify.formatter.impl` too. I have checked that `(numeral-format lower-roman 9)` works in an `evaluate` that is inside a `toc-entry-on-resumed`.

**Comment by kalaspuffar** [comment]
If we already have functionality I vote to close these PRs as we don't want to add extra complexity.

**Comment by PaulRambags** [comment]
As a matter of fact, we might even consider to entirely remove the `number-format` attribute from the OBFL specification language. It is sufficient to use an `evaluate` everywhere and the `numeral-format` function in the OBFL evaluation language. But that is maybe a step too far.

**Comment by bertfrees** [comment]
@kalaspuffar I suggested to Paul to let it sink a few days before closing PRs and reverting stuff. Even though the new attribute is redundant, it may be a good addition to the spec. One thing to keep in mind that it is not so straightforward to decide which functionality belongs in OBFL itself and which functionality belongs in the OBFL evaluation language. There is obviously some possible overlap between the two.

**Comment by kalaspuffar** [comment]
> @kalaspuffar I suggested to Paul to let it sink a few days before closing PRs and reverting stuff. Even though the new attribute is redundant, it may be a good addition to the spec. One thing to keep in mind that it is not so straightforward to decide which functionality belongs in OBFL itself and which functionality belongs in the OBFL evaluation language. There is obviously some possible overlap between the two.

Well @bertfrees, you are right in that this addition could have value for readability and ease of use. It all depends on how hard another solution is to find and how common the function is. If let's say 1% of all production has these roman numbers, then an additional attribute might not be needed.

If we, on the other hand, have 30-60% of production using it, then it might be required not to have extreme amounts of expressions in the OBFL files. 

OBFL should be humanly readable, but other tools mostly generate it, so having some extra overhead when creating information might not be a big deal.

**Comment by PaulRambags** [comment]
As agreed, this PR was closed without merging the changes.

**Pull request closed without merging**
